"""added plaid_transaction_id

Revision ID: de5d2bc61845
Revises: 805465afc441
Create Date: 2025-10-07 11:20:56.517407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5d2bc61845'
down_revision: Union[str, Sequence[str], None] = '805465afc441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plaid_transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'plaid_transaction_id')
    # ### end Alembic commands ###
